### ISSUE TITLE
Mobile route/stop selector and view

### ISSUE THREAD

**Issue by sherson** [umts/BusInfoBoard#21]
### Page to select routes/stops
- If location awareness enabled, shows 5-10 of the closest stops
- Routes selector (if route selected, list stops for route)
- Links (www.twitter.com/umasstransit, www.umass.edu/transit)
### Mobile view of BusInfoBoard
- No animations
- Updates more frequently
- Smaller font?
- Link(s)

**Comment by bcspragu** [comment]
Most of the stop selection stuff was addressed with https://github.com/umts/BusInfoBoard/commit/85ff3a6878927930cc0adb721086794f12a7f990

Mobile changes for BusInfoBoard are still in the pipeline

**Comment by sherson** [comment]
Looks great. We talked about clarifying things a bit... possibly with something like:

```
Choose from nearest stop(s)
[list]
-----------------------------
Or 
-----------------------------
Filter by route(s)
[list]
Then choose stop(s)
[list]
-----------------------------
[View Departures]
```

**Comment by sherson** [comment]
We talked about adding a title or logo on the stop selector/mobile view.

**Comment by sherson** [comment]
We also talked about adding alerts from http://bustracker.pvta.com/InfoPoint/rest/PublicMessages/GetCurrentMessages. Ideally, it would show:

* Messages that aren't associated with any route(s)
* Messages that are associated with route(s) in the results

And not show 

* Messages associates with route(s) that aren't in the results

On a different page.

**Comment by sherson** [comment]
Regarding http://bustracker.pvta.com/InfoPoint/rest/PublicMessages/GetCurrentMessages, we can ignore `<DaysOfWeek>`, `<From/toDate/Time>`, `<Published>`, and `<PublicAccess>`.

We pretty much just care about `<Message>` and `<Routes>`.

**Comment by sherson** [comment]
Looks great, but the Alerts icon disappears on page refresh.

**Comment by sherson** [comment]
Thanks @dfaulken 8607c8fe2fa5b71cfa799a42e04de92c366bad0a

**Comment by werebus** [comment]
Does this issue have anything unresolved in it?

**Comment by werebus** [comment]
I guess not
