### ISSUE TITLE
LocalStorage?

### ISSUE THREAD

**Issue by werebus** [umts/BusInfoBoard#31]
It occurred to me while looking over #30, that there are some things (list of stops, etc) that don't change in our system very often.  [Modern browsers](http://caniuse.com/#search=localStorage) have [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API) available to them.  I wonder if it's worth the complexity/latency tradeoff?

**Comment by akaplo** [comment]
When you say "don't change in our system," do you mean the information about the stops themselves doesn't change, or the departures don't change?  I think that's a good thing to look into regardless, especially for users on metered connections.

**Comment by werebus** [comment]
Sorry, yes.  I mean things like, "what stops do we have?" and, "What are our route names and directions?"  The list of all stops seems like a good possible candidate.
