### ISSUE TITLE
Two css and js directories

### ISSUE THREAD

**Issue by werebus** [umts/BusInfoBoard#32]
I'm not really sure why the StopSelector needs its own set of css and js directories.  A restructure here could be worthwhile.

**Comment by akaplo** [comment]
I'll look into that soon.  Also @werebus when you gave me access to the AvailDocs repository on Monday...you never actually gave me access to it.

**Comment by werebus** [comment]
Sorry.  I forgot that you weren't a "Transit Programmer" yet.  Fixed now.

**Comment by werebus** [comment]
Actually, now that umts/pvta-multiplatform is a thing, I think the stop selector can just be deleted.
