### ISSUE TITLE
MyAvail feed changing 2016-01-24

### ISSUE THREAD

**Issue by sherson** [umts/BusInfoBoard#40]
It's possible we won't need to do anything, but I found out yesterday afternoon that the upcoming MyAvail upgrade (going live on Sunday, 1/24) means their feed is changing slightly. I asked Avail for a list of changes.

PVTA has a [test URL](http://test.pvta.com:81/InfoPoint/rest/), and [new documentation](http://test.pvta.com:81/InfoPoint/swagger/ui/index) (the documentation is currently broken; Avail said it's the same as [CATABUS](http://realtime.catabus.com/InfoPoint/swagger/ui/index), except for *"the signage departures rest endpoint"*).

The viewer and stop selector worked fine when I [changed] (https://github.com/umts/BusInfoBoard/blob/master/js/main.js#L11) [them](https://github.com/umts/BusInfoBoard/blob/master/StopSelector/js/main.js#L5) locally to the test URL

On a side note, PVTA has [their own version of BusInfoBoard](http://pvtaapps.com/kiosk/sbt/test/?stops=9002&sort=time). They initially contacted me because it wasn't working yesterday (but apparently it was a connectivity issue, and it's been working fine since). 

PVTA confirmed that the URL will not change.

`PublicMessages/GetCurrentMessages` hasn't been tested yet.

**Comment by dfaulken** [comment]
Will we be able to keep in contact with them about precisely when the change is occurring? It'd be nice to monitor the BIB to make sure there are no issues.

**Comment by sherson** [comment]
> Will we be able to keep in contact with them about precisely when on Sunday 1/24 the change is occurring? It'd be nice to monitor the BIB to make sure there are no issues.

Yes

**Comment by sherson** [comment]
The switch is happening after service ends on Saturday... so on Sunday morning, the new MyAvail environment will be in production. 

Avail will be onsite during the switch, and for a couple days afterwards.

**Comment by sherson** [comment]
Documentation is now available at http://bustracker.pvta.com/InfoPoint/swagger/ui/index (ignore the signage portions).
