### ISSUE TITLE
Remove non-departure code

### ISSUE THREAD

**Issue by werebus** [umts/BusInfoBoard#41]
In my opinion, given that [umts/pvta-multiplatform](/umts/pvta-multiplatform) exists, we don't need this application to be a mobile app too.  I propose removing the stop-selector.

I'm on the fence about the alert icon; certainly we want to change the determiner from `mobile=true` to something else, but I can think of situations (touch screens?) where we might want it.

Opinions?

**Comment by sherson** [comment]
StopSelector might still be handy for choosing which stops to display... is there a reason not to keep it and move it from http://umts.github.io/BusInfoBoard/StopSelector/ to http://umts.github.io/BusInfoBoard?

I'm also on the fence about the alert icon, but my inclination is to keep it (as you point out, it'd be useful on an interactive kiosk).

**Comment by werebus** [comment]
Who is doing this "choosing," though? The reason not to keep it is that its approximately 50% of the code base in this application and isn't used by anyone (as far as I know).

Moving the stop selector to the root of the site means moving the **departure board** away from the root of the site which breaks any existing departure boards out there (until they update the URL).

**Comment by sherson** [comment]
I occasionally use it to look up stops when checking for problems in the feed (it's a slick UI), and it'd be a convenient way for those less familiar with our service to setup real-time displays.

However, it's used very infrequently, so if it ends up being too much trouble to keep StopSelector, we can get rid of it (and advise people to use [PVTrAck](https://m.pvta.com) and to contact us with questions).
