### ISSUE TITLE
Alternate time-humanizing?

### ISSUE THREAD

**Issue by werebus** [umts/BusInfoBoard#47]
I've been playing with #42, and noticed that a lot of the display is devoted to the word, "minutes." It turns out you can customize those strings with your [locale settings][1].

It *doesn't* change the fact that [45 minutes is an hour][2], though.

For small screens perhaps:

```javascript
moment.updateLocale('en', {
    relativeTime : {
        future: "in %s",
        past:   "%s ago",
        s:  "<1 min",
        m:  "1 min",
        mm: "%d mins",
        h:  "1 hr",
        hh: "%d hrs",
        d:  "1 day",
        dd: "%d days",
        M:  "1 mo",
        MM: "%d mos",
        y:  "1 yr",
        yy: "%d yrs"
    }
});
```

[1]:  https://momentjs.com/docs/#/customization/relative-time/
[2]:  https://momentjs.com/docs/#/displaying/tonow/

**Comment by dfaulken** [comment]
Perhaps just translate everything to hours and minutes? We don't show departures more than 2 or 3 hours out anyhow.

**Comment by dfaulken** [comment]
@Anbranin will write up a feature branch for us to compare this suggestion with the current view.

**Comment by dfaulken** [comment]
#53
