### ISSUE TITLE
Maintain master/gh-pages separation?

### ISSUE THREAD

**Issue by werebus** [umts/BusInfoBoard#48]
GitHub now allows you to serve you GH Pages site [right off of `master`][1]. Do we want to keep both a `gh-pages` branch *and* a `master` branch?

[1]:  https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/

**Comment by dfaulken** [comment]
Probably not.

**Comment by werebus** [comment]
I tend to agree.  The only advantage to having both is that it draws the distinction between "master" and "deployed."  But, I mean, we shouldn't be merging code to master that we don't want deployed, right?

**Comment by werebus** [comment]
And done.  `master` is now the official version.
