### ISSUE TITLE
Show Public Messages

### ISSUE THREAD

**Issue by sherson** [umts/BusInfoBoard#71]
We've talked a few times about rendering public messages for routes that are servicing the chosen stop(s). A consideration is spacing... there can be multiple messages (up to 255 characters each) and we often display multiple stops. Perhaps we could have a flag to:

1. Show departures
2. Show messages
3. Show both (default)

Other notes: 
* We used to do this in the [decommissioned](https://github.com/umts/BusInfoBoard/pull/44) interactive mobile version (though it required the user to tap an icon).
* We briefly discussed trying to figure out which routes service a stop (in case a route isn't servicing it in the next 2-3 hours), but we think the overhead might be too great with [Stops_GetAllStopsForRoutes](
https://bustracker.pvta.com/InfoPoint/swagger/ui/index#!/Stops/Stops_GetAllStopsForRoutes), and anyway just showing messages for currently displayed routes (as well as general messages) ought to be fine.

@dfaulken is working on it.

**Comment by sherson** [comment]
BTW, for reference: an example of it not running fullscreen: http://eco.umass.edu/kiosk/db/

**Comment by sherson** [comment]
Reopening this with a question:

Currently, all the routes that a public message is associated with are listed, even if some of those routes do not service the selected stop(s). 

Is this confusing, and should we instead only show routes (next to a public message) that have departures listed? 

There are pros and cons to each approach, one con being that trimming a public message routes list to only those with departures shown could result in a situation where we exclude a route that services the selected stop(s), but isn't listed because it doesn't have any upcoming departures. Maybe that's more confusing, but it'd probably be fine because the public message would still be shown.

**Comment by dfaulken** [comment]
From a technical standpoint, it's certainly possible to do. However, I don't really see the confusion. Have we received feedback about this?

And, I don't like the idea of detours being presented inconsistently (as if they apply to different sets of routes) depending on what stop you're waiting at.

**Comment by sherson** [comment]
We haven't received feedback.

While looking at Smith, it struck me as a little odd seeing R41 and B48 listed next to the public message when those routes don't service that stop. Maybe it's fine, but perhaps a passenger could get confused and think that those routes service that stop?

![businfoboard with avail public messages for other routes](https://user-images.githubusercontent.com/409008/34570469-e450df4a-f139-11e7-89f5-daf06166dcfa.png)

However, if the public message text also has the routes listed, then it might be even more confusing to selectively list the routes on the left. 

For example, stop [828](http://umts.github.io/BusInfoBoard/?stops=828), is only serviced by B6:

![businfoboard with avail public messages for other routes 828](https://user-images.githubusercontent.com/409008/34570730-a75c80ca-f13a-11e7-9306-4ea903ca49fa.png)

If the text was 

> B6: G3, G5, and B6 buses are avoiding Chestnut St and continuing to State and Main both inbound and outbound. Stops missed on Chestnut St and Harrison Ave.

that would also be inconsistent (and arguably worse). 

If PVTA and all the operators were consistent about text conventions, we could avoid that. But I think we should leave it as is, so never mind. Closing.
