### ISSUE TITLE
StopStatusReportLabel skipped

### ISSUE THREAD

**Issue by sherson** [umts/BusInfoBoard#78]
`<StopStatusReportLabel>Skipped</StopStatusReportLabel>` in StopDepartures means that departure is skipped, so we should not show it. 

We have several trippers canceled today, which you can see at stops such as https://bustracker.pvta.com/InfoPoint/rest/StopDepartures/Get/56.

**Comment by bandogora** [comment]
@sherson I don't see any `StopStatusReportLabel` with the value `Skipped`, were they removed? I see the trippers but their status is `Scheduled`.

**Comment by sherson** [comment]
No trippers (or other blocks) were canceled today, and no detours are in effect. Those are the two common cases for `Skipped` (that we're aware of).

**Comment by sherson** [comment]
Also, though I've only ever seen a status of `Skipped` or `Scheduled`, there may be others. So we should not show it if it's `Skipped` (rather than only showing it if it's `Scheduled`).
